services:
  caddy:
    image: caddy:2.9-alpine
    container_name: caddy_proxy
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/data:/data
      - ./caddy/config:/config
      - ./caddy/conf:/conf
      - ./caddy/site:/site
    networks:
      - caddy_proxy_net
    env_file: "caddy/caddy.env"

  whoami:
    image: traefik/whoami
    container_name: whoami
    restart: unless-stopped
    command:
       - --name=biixie
    networks:
      - caddy_proxy_net

networks:
  caddy_proxy_net:
