name: Deploy Production

on:
  push:
    branches:
      - main

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_PRIVATE_KEY }}
          script: |
            echo "Checking out remote repository"
            cd ${{ vars.STACK_DIRPATH }}
            git fetch --all
            git reset --hard origin/main
            
            echo "Deploying stack"
            docker stack deploy --compose-file ${{ vars.STACK_FILEPATH }} ${{ vars.STACK_NAME }} --prune
